on:
  create:
    ref_type: "tag"
#   release:
#     types: 
#       - created
      
name: Mark Jira tickets as Production  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira ticket integration
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://runai.atlassian.net/
          JIRA_USER_EMAIL: jira-bot@run.ai
          JIRA_API_TOKEN: ${{ secrets.JIRA_SECRET }}
      - name: Setup Jira CLI
        uses: atlassian/gajira-cli@v2.0.2
      - name: Run CLI
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          export JIRA_API_TOKEN=${{ secrets.JIRA_SECRET }}
          echo "$GITHUB_REPOSITORY"
          jira list -q "\"Code status[Short text]\" ~ \"Master\" AND comment ~ \"repository: $GITHUB_REPOSITORY\"" | sed 's/:.*//' > /tmp/tickets-to-update.txt
          while read p; do
            jira comment "$p" --noedit --comment="tagged-for-production. tag: $RELEASE_VERSION"
          done < /tmp/tickets-to-update.txt

